version: '3.5'
services: 
    db: 
        build: 
            dockerfile: Dockerfile
            context: ./UVFYDB
        environment:
            SA_PASSWORD: "HelloWorld10"
            ACCEPT_EULA: "Y"
        container_name: UVFYDB
    auth: 
        build:
            dockerfile: Dockerfile
            context: ./UVFYAuth
        container_name: UVFYAuth
    sesion: 
        build: 
            dockerfile: Dockerfile
            context: ./UVFYSesion
        container_name: UVFYSesion
    conversion:
        build: 
            dockerfile: Dockerfile
            context: ./UVFYGuardadoDeArchivos
        container_name: UVFYGuardadoDeArchivos
    archivos:
        build: 
            dockerfile: Dockerfile
            context: ./UVFYArchivos
        container_name: UVFYArchivos
    metadatos:
        build: 
            dockerfile: Dockerfile
            context: ./UVFYMetadatos
        container_name: UVFYMetadatos
    gateway:
        build: 
            dockerfile: Dockerfile
            context: ./UVFYGateway
        ports:
            - "7001:80"
            - "7002:443"
        container_name: UVFYGateway